import { useEffect,useState } from 'react'
import { useSearchParams, Link } from 'react-router-dom'
import { Search } from 'lucide-react'
import Navbar from '../components/common/Navbar'
import Footer from '../components/common/Footer'
import ShopCard from '../components/mall/ShopCard'
import AsyncState from '../components/mall/AsyncState'
import { categories } from '../utils/mall'
import api from '../utils/api'
export default function BrowsePage(){
 const [params,setParams]=useSearchParams(),[data,setData]=useState({items:[],total:0}),[state,setState]=useState('loading'),[query,setQuery]=useState(params.get('q')||''),[retry,setRetry]=useState(0)
 const cat=params.get('cat')||'',page=Number(params.get('page'))||1,key=params.toString()
 useEffect(()=>{setQuery(params.get('q')||'');const controller=new AbortController();setState('loading');api.get('/catalogue/shops',{params:{q:params.get('q')||'',category:cat||undefined,page,page_size:24},signal:controller.signal}).then(r=>{setData(r.data);setState('ready')}).catch(e=>{if(e.code!=='ERR_CANCELED')setState('error')});return()=>controller.abort()},[key,retry])
 const change=(values)=>{const next=new URLSearchParams(params);next.delete('page');Object.entries(values).forEach(([k,v])=>v?next.set(k,v):next.delete(k));setParams(next)}
 return <><Navbar/><main id="mall-content" className="container mall-main"><div className="mall-page-heading"><span className="mall-eyebrow">THE SHOP DIRECTORY</span><h1>Many shops. One local mall.</h1><p>Step inside a shop to discover its products, services and story.</p></div><form className="mall-catalogue-search" onSubmit={e=>{e.preventDefault();change({q:query.trim()})}}><Search size={20}/><input aria-label="Search shops" placeholder="Find a shop by name or location…" value={query} onChange={e=>setQuery(e.target.value)}/><button type="submit" className="btn btn-primary">Search</button></form><div className="mall-tablinks"><button aria-pressed={!cat} className={!cat?'selected':''} onClick={()=>change({cat:''})}>All shops</button>{categories.map(c=><button key={c.id} aria-pressed={cat===c.id} className={cat===c.id?'selected':''} onClick={()=>change({cat:c.id})}>{c.label}</button>)}</div><p className="mall-result-count" role="status">{state==='ready'?`${data.total} shops to explore`:'Finding shops…'}</p><AsyncState loading={state==='loading'} error={state==='error'} empty={!data.items.length} retry={()=>setRetry(x=>x+1)}><div className="mall-shop-grid">{data.items.map(shop=><ShopCard key={shop.id} shop={shop}/>)}</div></AsyncState>{data.total>24&&<nav className="mall-pagination" aria-label="Shop pages"><button className="btn btn-secondary" disabled={page<=1} onClick={()=>{setParams(p=>{p.set('page',String(page-1));return p});window.scrollTo({top:0})}}>Previous</button><span>Page {page} of {Math.ceil(data.total/24)}</span><button className="btn btn-secondary" disabled={page*24>=data.total} onClick={()=>{setParams(p=>{p.set('page',String(page+1));return p});window.scrollTo({top:0})}}>Next</button></nav>}<section className="mall-collection-callout"><div><h2>Is your shop missing?</h2><p>Give your local business a home in the mall.</p></div><Link to="/sell" className="btn btn-primary">Open your shop</Link></section></main><Footer/></>
}
