import { useEffect,useState } from 'react'
import { useParams,Link } from 'react-router-dom'
import { MapPin, Clock3, MessageCircle, Store, ArrowLeft } from 'lucide-react'
import Navbar from '../components/common/Navbar'
import Footer from '../components/common/Footer'
import ItemCard from '../components/mall/ItemCard'
import AsyncState from '../components/mall/AsyncState'
import SaveButton from '../components/mall/SaveButton'
import { categoryLabel } from '../utils/format'
import { mediaUrl,whatsappLink } from '../utils/mall'
import api from '../utils/api'
export default function BusinessPage(){
 const {slug}=useParams(),[shop,setShop]=useState(null),[state,setState]=useState('loading'),[tab,setTab]=useState(''),[query,setQuery]=useState(''),[retry,setRetry]=useState(0)
 useEffect(()=>{let live=true;setState('loading');setTab('');setQuery('');api.get(`/businesses/${slug}`).then(r=>{if(live){setShop(r.data);setState('ready');document.title=`${r.data.name} · Loxion Mart`}}).catch(e=>{if(live)setState(e.response?.status===404?'missing':'error')});return()=>{live=false;document.title='Loxion Mart — Shop Local, Shop Lekker!'}},[slug,retry])
 const items=(shop?.services||[]).filter(s=>s.is_available&&(!tab||s.service_type===tab)&&[s.name,s.description].some(v=>(v||'').toLowerCase().includes(query.toLowerCase())))
 const wa=shop?whatsappLink(shop,`Hi ${shop.name}! I found your shop on Loxion Mart.`):''
 return <><Navbar/><main id="mall-content" className="container mall-main"><Link to="/browse" className="mall-back"><ArrowLeft size={16}/>All shops</Link>{state==='missing'?<div className="mall-empty"><h1>This shop is currently unavailable.</h1><Link to="/browse" className="btn btn-primary">Explore other shops</Link></div>:<AsyncState loading={state==='loading'} error={state==='error'} retry={()=>setRetry(x=>x+1)}>{shop&&<><div className={`mall-shop-cover ${shop.cover_url?'has-cover':''}`}>{shop.cover_url?<img src={mediaUrl(shop.cover_url)} alt={`${shop.name} shop banner`} width="1200" height="300" onError={e=>{e.currentTarget.style.display='none'}}/>:<><Store size={44}/><span>WELCOME TO {shop.name.toUpperCase()}</span></>}</div><section className="mall-storefront-header"><div className="mall-storefront-title">{shop.logo_url&&<img src={mediaUrl(shop.logo_url)} alt={`${shop.name} logo`} width="88" height="88"/>}<div><span className="mall-eyebrow">{categoryLabel(shop.category)}</span><h1>{shop.name}</h1><p className="mall-location"><MapPin size={16}/>{shop.location||'Local business'}</p></div></div><div className="mall-storefront-actions"><SaveButton kind="shop" id={shop.id} label={shop.name} text/>{wa&&<a className="btn btn-primary" href={wa} target="_blank" rel="noopener noreferrer"><MessageCircle size={17}/>Contact the shop</a>}</div></section><p className="mall-shop-story">{shop.description}</p><div className="mall-shop-info"><details><summary>About this shop & how to order</summary><div className="mall-info-grid"><div><h3>Opening hours</h3><p>{shop.opening_hours||'Contact the shop to confirm opening hours.'}</p></div><div><h3>Collection</h3><p>{shop.collection_info||'Confirm collection arrangements with the shop.'}</p></div><div><h3>Delivery</h3><p>{shop.delivery_info||'Ask the shop about delivery availability and fees.'}</p></div><div><h3>Returns & cancellations</h3><p>{shop.returns_info||'Request the shop’s policy before ordering or booking.'}</p></div></div></details></div><section className="mall-section"><div className="mall-section-head"><h2>Inside the shop</h2><span>{items.length} listings</span></div><div className="mall-shop-controls"><div className="mall-tablinks"><button onClick={()=>setTab('')} className={!tab?'selected':''}>Everything</button><button onClick={()=>setTab('product')} className={tab==='product'?'selected':''}>Products</button><button onClick={()=>setTab('booking')} className={tab==='booking'?'selected':''}>Services</button></div><input className="form-input" aria-label="Search this shop" placeholder="Search this shop…" value={query} onChange={e=>setQuery(e.target.value)}/></div><AsyncState empty={!items.length}><div className="mall-item-grid">{items.map((item,i)=><ItemCard key={item.id} item={{...item,business:shop}} eager={i<4}/>)}</div></AsyncState></section></>}</AsyncState>}</main><Footer/></>
}
