import { Link } from 'react-router-dom'
import { Minus,Plus,Trash2,ShoppingBag } from 'lucide-react'
import Navbar from '../components/common/Navbar'
import Footer from '../components/common/Footer'
import ItemImage from '../components/mall/ItemImage'
import useCartStore from '../store/cartStore'
import { formatPrice } from '../utils/format'
import { whatsappLink } from '../utils/mall'
export default function CartPage(){
 const {items,removeItem,updateQuantity,total}=useCartStore()
 const groups=Object.values(items.reduce((acc,i)=>{const id=i.business.id;if(!acc[id])acc[id]={business:i.business,items:[]};acc[id].items.push(i);return acc},{}))
 return <><Navbar/><main id="mall-content" className="container mall-main"><div className="mall-page-heading"><span className="mall-eyebrow">YOUR MALL BASKET</span><h1>A little from here. A little from there.</h1><p>Items are grouped by shop, so you always know who you’re buying from.</p></div>{!items.length?<div className="mall-empty"><ShoppingBag size={34}/><h2>Your basket is waiting for something local.</h2><Link to="/mall?kind=product" className="btn btn-primary">Shop products</Link></div>:<div className="mall-basket-layout"><div>{groups.map(({business,items:shopItems})=><section className="mall-basket-shop" key={business.id}><div className="mall-section-head"><h2>{business.slug?<Link to={`/business/${business.slug}`}>{business.name}</Link>:business.name}</h2><span>{shopItems.length} items</span></div>{shopItems.map(({service,quantity})=><div className="mall-basket-item" key={service.id}><Link to={`/item/${service.id}`}><ItemImage url={service.image_urls?.[0]} name={service.name}/></Link><div><Link to={`/item/${service.id}`}><h3>{service.name}</h3></Link><p>{formatPrice(service.price)} each</p><div className="mall-quantity"><button aria-label={`Decrease ${service.name} quantity`} onClick={()=>updateQuantity(service.id,quantity-1)}><Minus size={15}/></button><span>{quantity}</span><button aria-label={`Increase ${service.name} quantity`} disabled={quantity>=Math.min(99,service.stock_quantity??99)} onClick={()=>updateQuantity(service.id,quantity+1)}><Plus size={15}/></button></div></div><div className="mall-basket-item-end"><strong>{formatPrice(service.price*quantity)}</strong><button aria-label={`Remove ${service.name}`} onClick={()=>removeItem(service.id)}><Trash2 size={18}/></button></div></div>)}{whatsappLink(business,'')&&<a className="btn btn-secondary" target="_blank" rel="noopener noreferrer" href={whatsappLink(business,`Hi ${business.name}, I found these on Loxion Mart. Please confirm availability and collection/delivery: ${shopItems.map(i=>`${i.quantity} × ${i.service.name}`).join(', ')}.`)}>Enquire with this shop</a>}</section>)}</div><aside className="mall-basket-summary"><h2>Basket summary</h2><div><span>{groups.length} local shops</span><strong>{formatPrice(total())}</strong></div><p>Estimated item total. Stock, final prices and any delivery costs must be confirmed with each shop.</p><div className="mall-notice"><strong>Online checkout is coming later.</strong><p>Your basket stays on this device. No order has been placed and no payment is taken.</p></div><Link className="btn btn-primary btn-full" to="/mall">Keep exploring</Link><Link className="btn btn-secondary btn-full" to="/saved">View saved favourites</Link></aside></div>}</main><Footer/></>
}
