import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { ArrowRight, ShoppingBag, CalendarDays, Store, Heart, MapPin, CheckCircle2 } from 'lucide-react'
import Navbar from '../components/common/Navbar'
import Footer from '../components/common/Footer'
import ItemCard from '../components/mall/ItemCard'
import ShopCard from '../components/mall/ShopCard'
import AsyncState from '../components/mall/AsyncState'
import { useSaved } from '../components/mall/SavedProvider'
import { recentIds } from '../utils/mall'
import api from '../utils/api'
export default function HomePage() {
  const [data,setData] = useState({ products:[], services:[], shops:[] }), [state,setState] = useState('loading'), [recent,setRecent] = useState([])
  const saved = useSaved()
  async function load() {
    setState('loading')
    try { const [p,s,b] = await Promise.all([api.get('/catalogue?kind=product&page_size=8'), api.get('/catalogue?kind=booking&page_size=4'), api.get('/catalogue/shops?page_size=4')]); setData({ products:p.data.items,services:s.data.items,shops:b.data.items }); setState('ready') } catch { setState('error') }
  }
  useEffect(() => { load(); Promise.allSettled(recentIds().map(id=>api.get(`/catalogue/${id}`))).then(results=>setRecent(results.filter(r=>r.status==='fulfilled').map(r=>r.value.data).slice(0,4))) }, [])
  return <><Navbar/><main id="mall-content"><div className="container"><section className="mall-welcome"><div><span className="mall-eyebrow">YOUR LOCAL SHOPPING MALL. ONLINE.</span><h1>Shop Local,<br/><em>Shop Lekker!</em></h1><p>Products you need. Services you love.<br/>Local shops, all in one place.</p><div className="mall-hero-links"><Link className="btn btn-primary" to="/mall">Explore the mall <ArrowRight size={17}/></Link><Link className="mall-text-link" to="/sell">Bring your shop online</Link></div></div><img src="/mall-storefronts.webp" alt="An illustrated row of local shops representing the Loxion Mart online mall" width="1536" height="1024" fetchPriority="high"/></section>
  <nav className="mall-entrances" aria-label="Start shopping"><Link to="/mall?kind=product"><ShoppingBag size={23}/><span><strong>Shop products</strong><small>Find your next local buy</small></span><ArrowRight size={19}/></Link><Link to="/mall?kind=booking"><CalendarDays size={23}/><span><strong>Book a service</strong><small>Make time for what you need</small></span><ArrowRight size={19}/></Link><Link to="/browse"><Store size={23}/><span><strong>Explore the shops</strong><small>Meet your local businesses</small></span><ArrowRight size={19}/></Link></nav>
  <section className="mall-section"><div className="mall-section-head"><div><span className="mall-eyebrow">FRESH FROM OUR SHOPS</span><h2>On the shelves</h2></div><Link to="/mall?kind=product">All products <ArrowRight size={17}/></Link></div><AsyncState loading={state==='loading'} error={state==='error'} empty={!data.products.length} retry={load}><div className="mall-item-grid">{data.products.map((item,i)=><ItemCard key={item.id} item={item} eager={i<4}/>)}</div></AsyncState></section>
  <section className="mall-collection-callout"><div className="mall-collection-icon"><Heart size={28}/></div><div><span className="mall-eyebrow">MAKE THIS MALL YOURS</span><h2>Your favourites, all together.</h2><p>Save something you love. Follow a shop. Pick up where you left off.</p></div><Link to="/saved" className="btn btn-secondary">{saved.keys.length ? `Your collection (${saved.keys.length})` : 'Start your collection'} <ArrowRight size={17}/></Link></section>
  <section className="mall-section"><div className="mall-section-head"><div><span className="mall-eyebrow">MORE THAN SHOPPING</span><h2>Good people. Great services.</h2></div><Link to="/mall?kind=booking">All services <ArrowRight size={17}/></Link></div><AsyncState loading={state==='loading'} error={state==='error'} empty={!data.services.length} retry={load}><div className="mall-item-grid">{data.services.map(item=><ItemCard key={item.id} item={item}/>)}</div></AsyncState></section>
  {recent.length>0&&<section className="mall-section"><div className="mall-section-head"><div><span className="mall-eyebrow">YOUR RECENT DISCOVERIES</span><h2>Take another look</h2></div><button className="mall-text-link" onClick={()=>{localStorage.removeItem('loxion-recent');setRecent([])}}>Clear recent history</button></div><p className="mall-muted mall-section-note">Recently viewed on this device.</p><div className="mall-item-grid">{recent.map(item=><ItemCard key={item.id} item={item}/>)}</div></section>}
  <section className="mall-section"><div className="mall-section-head"><div><span className="mall-eyebrow">EVERY SHOP HAS A STORY</span><h2>Step into a local shop</h2></div><Link to="/browse">All shops <ArrowRight size={17}/></Link></div><AsyncState loading={state==='loading'} error={state==='error'} empty={!data.shops.length} retry={load}><div className="mall-shop-grid">{data.shops.map(shop=><ShopCard key={shop.id} shop={shop}/>)}</div></AsyncState></section>
  <section id="how-it-works" className="mall-how"><div><ShoppingBag/><h3>Browse before you join</h3><p>Explore shops, compare listings and read the details freely.</p></div><div><Heart/><h3>One account. Your mall.</h3><p>Keep favourites and followed shops together across devices.</p></div><div><CalendarDays/><h3>Connect with the shop</h3><p>Request a service appointment or ask about an item. Online payments will follow.</p></div></section>
  <section className="mall-owner-callout"><div><span className="mall-eyebrow">SMALL BUSINESS. BIG LOCAL ENERGY.</span><h2>Your shop belongs<br/>in this mall.</h2><p>A storefront for your products, your services and your story.</p></div><Link to="/sell" className="btn btn-light">Open your shop <ArrowRight size={19}/></Link></section></div></main><Footer/></>
}
