import { useEffect,useState } from 'react'
import { useParams,Link } from 'react-router-dom'
import { ShoppingBag, Check, MapPin, Share2, MessageCircle, ArrowLeft } from 'lucide-react'
import { toast } from 'react-hot-toast'
import Navbar from '../../components/common/Navbar'
import Footer from '../../components/common/Footer'
import ItemImage from '../../components/mall/ItemImage'
import ItemCard from '../../components/mall/ItemCard'
import SaveButton from '../../components/mall/SaveButton'
import AsyncState from '../../components/mall/AsyncState'
import BookingForm from '../../components/mall/BookingForm'
import useCartStore from '../../store/cartStore'
import { formatPrice,categoryLabel } from '../../utils/format'
import { rememberItem,whatsappLink } from '../../utils/mall'
import api from '../../utils/api'
export default function ItemPage(){
 const {id}=useParams(),[item,setItem]=useState(null),[state,setState]=useState('loading'),[active,setActive]=useState(0),[related,setRelated]=useState([]),[qty,setQty]=useState(1),[added,setAdded]=useState(false),[retry,setRetry]=useState(0)
 const addItem=useCartStore(s=>s.addItem)
 useEffect(()=>{let cancelled=false;setState('loading');setActive(0);setAdded(false);setQty(1);api.get(`/catalogue/${id}`).then(async r=>{if(cancelled)return;setItem(r.data);setState('ready');rememberItem(r.data.id);document.title=`${r.data.name} · Loxion Mart`;try{const rel=await api.get('/catalogue',{params:{shop_id:r.data.business_id,page_size:5}});if(!cancelled)setRelated(rel.data.items.filter(x=>x.id!==r.data.id).slice(0,4))}catch{setRelated([])}}).catch(e=>{if(!cancelled)setState(e.response?.status===404?'missing':'error')});return()=>{cancelled=true;document.title='Loxion Mart — Shop Local, Shop Lekker!'}},[id,retry])
 async function share(){try{if(navigator.share)await navigator.share({title:item.name,url:window.location.href});else{await navigator.clipboard.writeText(window.location.href);toast.success('Link copied')}}catch(err){if(err.name!=='AbortError')toast.error('Copy this page’s address to share it.')}}
 const product=item?.service_type==='product',wa=item?whatsappLink(item.business,`Hi! I found ${item.name} on Loxion Mart. ${window.location.href}`):''
 function add(){const result=addItem(item,item.business,qty);if(result.unavailable){toast.error('That quantity is not available.');return}setAdded(true);toast.success('Added to your mall basket')}
 return <><Navbar/><main id="mall-content" className="container mall-main"><Link className="mall-back" to="/mall"><ArrowLeft size={16}/>Back to the mall</Link>{state==='missing'?<div className="mall-empty"><h1>This listing is no longer available.</h1><Link className="btn btn-primary" to="/mall">Explore the mall</Link></div>:<AsyncState loading={state==='loading'} error={state==='error'} retry={()=>setRetry(x=>x+1)}>{item&&<><div className="mall-detail"><section className="mall-gallery" aria-label={`${item.name} photos`}><ItemImage url={item.image_urls?.[active]} name={item.name} eager/>{item.image_urls.length>1&&<div className="mall-thumbnails">{item.image_urls.map((url,i)=><button key={url+i} onClick={()=>setActive(i)} aria-label={`View photo ${i+1}`} aria-pressed={active===i} className={active===i?'active':''}><ItemImage url={url} name={`${item.name}, photo ${i+1}`}/></button>)}</div>}</section><section className="mall-detail-info"><span className="mall-eyebrow">{categoryLabel(item.business.category)} · {product?'PRODUCT':'SERVICE'}</span><h1>{item.name}</h1><Link to={`/business/${item.business.slug}`} className="mall-detail-seller">From {item.business.name} →</Link><p className="mall-location"><MapPin size={15}/>{item.business.location||'Local shop'}</p><div className="mall-detail-price">{formatPrice(item.price)}{!product&&item.duration_minutes&&<small>{item.duration_minutes} minute service</small>}</div><p className="mall-availability">{product?item.stock_quantity===0?'Currently out of stock':item.stock_quantity!=null?'In stock':'Ask the shop about stock':'Appointment availability confirmed by the shop'}</p><p className="mall-description">{item.description||'Ask the shop for more information about this listing.'}</p>{product?<div className="mall-buy"><label htmlFor="item-quantity">Quantity</label><div><input id="item-quantity" type="number" min="1" max={Math.min(99,item.stock_quantity??99)} value={qty} onChange={e=>setQty(Math.max(1,Math.min(99,parseInt(e.target.value)||1)))}/><button className="btn btn-primary" disabled={item.stock_quantity===0} onClick={add}>{added?<Check size={18}/>:<ShoppingBag size={18}/>} {added?'Add another':'Add to basket'}</button></div><p className="mall-muted">Online checkout is coming later. Keep items in your basket or contact the shop to enquire.</p>{added&&<Link to="/cart" className="mall-text-link">View your basket →</Link>}</div>:<BookingForm key={item.id} item={item}/>}
 <div className="mall-detail-actions"><SaveButton id={item.id} label={item.name} text/><button className="btn btn-secondary" onClick={share}><Share2 size={17}/>Share</button>{wa&&<a className="btn btn-secondary" href={wa} target="_blank" rel="noopener noreferrer"><MessageCircle size={17}/>Ask the shop</a>}</div></section></div>
 <section className="mall-detail-extra"><div><h2>{product?'Details & specifications':'About this service'}</h2>{Object.keys(item.specifications).length?<dl className="mall-specs">{Object.entries(item.specifications).map(([key,value])=><div key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl>:<p className="mall-muted">The shop hasn’t added extra specifications yet. Contact them if you need a particular detail.</p>}</div><div><h2>From {item.business.name}</h2><details open><summary>Collection & delivery</summary><p>{item.business.collection_info||'Ask the shop about collection arrangements.'}</p><p>{item.business.delivery_info||'Delivery availability and any cost must be confirmed with the shop.'}</p></details><details><summary>Returns & service policies</summary><p>{item.business.returns_info||'Ask the shop about its returns, cancellation and service policies before making arrangements.'}</p></details></div></section>{related.length>0&&<section className="mall-section"><div className="mall-section-head"><h2>More from this shop</h2><Link to={`/business/${item.business.slug}`}>Visit the shop →</Link></div><div className="mall-item-grid">{related.map(x=><ItemCard key={x.id} item={x}/>)}</div></section>}</>}</AsyncState>}</main><Footer/></>
}
